name: Python Unit Tests

on:
  pull_request:

jobs:
  test:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.12'

      - name: Install Julia Dependencies
        run: |
          julia -e 'using Pkg; Pkg.add(["Arrow","DataFrames","Parquet","QuadGK"])'

      - name: Generate Quadrature Rules
        working-directory: doodler/quadrature
        run: |
          julia generate_quadrature_rules.jl

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-py-3.14-${{ hashFiles('requirements-python.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-py-3.14

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-python.txt

      - name: Run Python Unit Tests
        run: |
          python -m pytest -q
